baseURL       = "https://uiro-bi.github.io/uiro-roxo"
languageCode  = "en-us"
title         = "Uiro"
theme         = "roxo-hugo"
summarylength = 25

# Site Menus
[menu]
  # Navbar Menus
  [[menu.nav]]
    name    = "Home"
    url     = ""
    weight  = 1
  [[menu.nav]]
    name    = "Sobre"
    url     = "about"
    weight  = 2
  [[menu.nav]]
    name    = "Portfolio"
    url     = "portfolio"
    weight  = 3
  # [[menu.nav]]
  #   name    = "Blog"
  #   url     = "blog"
  #   weight  = 4
  [[menu.nav]]
    name    = "Contato"
    url     = "contact"
    weight  = 5

# Site Params
[params]
  logo = "images/new_logo.png"
  #logo_footer = "images/new_logo_footer.png"
  favicon_icon = "images/favicon.ico"
  favicon_shortcut_icon = "images/favicon.png"
  custom_stylesheets = []   # [ "scss/my_1.scss", "scss/my_2.scss" ]
  dateFormat = "26 FEB 1994"
  # Meta data
  description = "Roxo Hugo themes | Design Agency Template by StaticMania"
  author = "StaticMania"
  # Google Analitycs
  googleAnalitycsID = "Your ID"
  # We're using formspree.io for form handling, paste your formspree url below
  fabform  = "https://fabform.io/f/USAg2Jl"

  # Contact Form
  [params.contactForm]
    placeholder_first_name        = "Nome"
    placeholder_last_name         = "Sobrenome"
    placeholder_email             = "Email"
    placeholder_project_type      = "Project Type"
    placeholder_about_the_project = "About the Project"
    send_message                  = "Send Message"

    [[params.contactForm.projectType]]
      value = "gd"
      title  = "Graphics Design"
    [[params.contactForm.projectType]]
      value = "wd"
      title  = "Web Design"
  
  # Navbar Action Button
  [params.navAction]
    status  = true
    name    = "Get in touch"
    url     = "contact"
  

  # Banner Section
  [params.banner]
    enable                = true
    background_image      = "images/backgrounds/pastel-background.png"
    heading               = "Inteligência de mercado para a bioeconomia na Amazônia"
    tagline               = "Engenharia de dados de ponta a sua disposição"
    primary_button        = "Veja nosso trabalho"
    primary_button_url    = "portfolio"
    secondary_button      = "Contate-nos"
    secondary_button_url  = "contact"

  [params.blog]
    read_more             = "read more"

  [params.portfolio]
    enable    = true
    title     = "Nossos trabalhos recentes"
    subtitle  = "Inteligência de mercado da amazônia para amaz."
    view_project = "view project"
    more_works = "MORE WORKS"
    scroll_down = "scroll down"

  [params.call_to_action]
    enable              = true
    background_image    = "images/backgrounds/cta-background.jpg"
    title               = "Vamos Trabalhar Juntos"
    primary_button      = "Contate-nos"
    primary_button_url  = "contact"
    secondary_button    = "Veja nossos cases"
    secondary_button_url = "portfolio"

  [params.footer]
    params.footer.qr_print = false
    # Footer Contact Info
    [params.footer.contactInfo]
      title   = "Contato"
      address = "Belém - PA"
      phone   = "(91) 99300-1347"
      email   = "gabriel.pisa@uiro.io"
      # Footer Sitemap
      # [params.footer.sitemap]
      #   title   = "Navegue pelo Site"
      #   [[params.footer.sitemap.link]]
      #     name = "Sobre"
      #     url  = "about"
      #   [[params.footer.sitemap.link]]
      #     name = "Portfolio"
      #     url  = "portfolio"
      #   #[[params.footer.sitemap.link]]
      #   #  name = "Blog"
      #   #  url  = "blog"
      #   [[params.footer.sitemap.link]]
      #     name = "Contato"
      #     url  = "contact"
      # Footer Social Media
      [params.footer.social]
        title   = "Mídias Sociais"
        [[params.footer.social.link]]
          name = "Instagram"
          url  = "#"
      # Footer Service
      [params.footer.service]
        title       = "Ajudamos negócios:"
        description = "Soluções de captura de dados<br>produce valuable cultural content<br>create fresh brand experience"
      [params.footer.back_to_top]
        description = "Volte para<br> o início do site"
